---
# Directory for creating the sdist tarball
securedrop_app_code_prep_dir: "/tmp/{{ securedrop_app_code_deb }}-prep"

# SecureDrop code installation directory
securedrop_code: /var/www/securedrop

# Location of the application storage on disk, including database.
securedrop_data: /var/lib/securedrop

# SecureDrop rq worker log directory
securedrop_worker_log_dir: /var/log/securedrop_worker

# SecureDrop user
securedrop_user: "www-data"

# Directory for building the Debian package
securedrop_app_code_deb_dir: "/tmp/securedrop-build"

securedrop_translation_pip_requirements: "{{ securedrop_app_code_deb_dir }}/requirements/python3/translation-requirements.txt"
securedrop_pip_requirements: "{{ securedrop_app_code_deb_dir }}/requirements/python3/requirements.txt"


securedrop_app_rsync_opts:
  - "--chmod=u=rwX,g=rX,o=rX"
  - "--chown=root:root"
  - "--exclude=*.git"
  - "--exclude=*.venv*"
  - "--exclude=*aths"
  - "--exclude=*.deb"

securedrop_local_build: "../../build"

# SecureDrop virtualenv location
securedrop_venv: "/opt/venvs/securedrop-app-code"
securedrop_venv_bin: "{{ securedrop_venv }}/bin"
securedrop_python_version: "3.8"
securedrop_venv_site_packages: "{{ securedrop_venv }}/lib/python{{ securedrop_python_version }}/site-packages"
